CVE-2022-20613/20614: Upgrade Mailer
openshift/jenkins-openshift-login-plugin pull request #125
Opened 2022-01-25 17:32 UTC by adambkaplan

Upgrade mailer to 408.vd726a_1130320 to address two vulnerabilities in
the plugin:

- CVE-2022-20613: CSRF vulnerability
- CVE-2022-20614: Missing permission check

2022-01-25 19:17 UTC, adambkaplan commented
@akram @gabemontero @jkhelil the image build is failing because it runs tests, resulting in the following errror:

```
Caused by: java.io.IOException: JavaBeans Activation Framework (JAF) API version 1.2.0-2 failed to load.
 - You must update Jenkins from version 2.164 to version 2.263.1 or later to run this plugin.
```

I have zero clue how to configure this...

2022-01-25 19:42 UTC, gabemontero requested changes
@adambkaplan you entire file here looks a bit out of date wrt https://github.com/openshift/jenkins-openshift-login-plugin/blob/master/pom.xml


for example, at line 11, the version noted is 1.0.17-SNAPSHOT

did you properly rebase your local clone ?

Now, the jenkins version dependency is noted at https://github.com/openshift/jenkins-openshift-login-plugin/blob/master/pom.xml#L24

per the error message you go, I would see you minimally bumping to the jenkins level noted though it might be good to just bump it to the version of jenkins we are bumping our image to.

2022-01-25 21:50 UTC, adambkaplan commented
@gabemontero after rebasing, took a few iterations to get the build to work.

2022-01-25 22:05 UTC, gabemontero commented
/lgtm

2022-01-25 22:05 UTC, gabemontero commented
/label docs-approved
no docs update needed

2022-01-25 22:06 UTC, gabemontero commented
/label px-approved

2022-01-25 22:06 UTC, gabemontero commented
/label qe-approved

qe is handled when we bump the login plugin version in openshift/jenkins and produce a new image

2022-01-25 23:59 UTC, gabemontero commented
/hold

something is up with this login plugin change @adambkaplan @akram and the existing e2e's

the last e2e failure at 
was in the part of the test where we try to get job logs:

```
    sync_plugin_test.go:368: pod logs for container hostexec in pod curl-job-pod:    % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                         Dload  Upload   Total   Spent    Left  Speed
        
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
100   847  100   847    0     0    817      0  0:00:01  0:00:01 --:--:--   817
        <html><head><meta http-equiv='refresh' content='1;url=/login?from=%2Fjob%2Fjenkins-sync-plugin-test-namespace-2vvzz%2Fjob%2Fjenkins-sync-plugin-test-namespace-2vvzz-sync-plugin-bc-env-var-override%2FlastBuild%2FconsoleText'/><script>window.location.replace('/login?from=%2Fjob%2Fjenkins-sync-plugin-test-namespace-2vvzz%2Fjob%2Fjenkins-sync-plugin-test-namespace-2vvzz-sync-plugin-bc-env-var-override%2FlastBuild%2FconsoleText');</script></head><body style='background-color:white; color:white;'>
        
        
        Authentication required
        <!--
        -->
        
        </body></html>                                                                                                                                                                                                                                                                                                            
```

this piece of the test is *THE* verification for the login plugin.  We have to exercise login plugin code to authenticate with jenkins via openshift oauth to get the data.

We are getting auth required errors.

That means some of the wiring we depend on in Jenkins has changed or something.

Someone will have to debug / investigate further.  Like build the plugin from the PR manually, the log into jenkins and install that built version of the plugin, and then diagnose what happens after jenkins reboot and you try to log back into the console, or fetch logs via curl, supplying the token for `kubeadmin` like the e2e's do.

2022-01-26 13:38 UTC, adambkaplan commented
/hold

Login plugin is reporting itself as failing. Need to determine what is causing it to break.

2022-01-26 15:16 UTC, adambkaplan commented
Testing this manually with cluster-bot, my local build of the plugin seems to work (I'm able to log back into the Jenkins console as kubeadmin).

2022-01-26 15:18 UTC, adambkaplan commented
This was an interesting pod log:

```
2022-01-26 15:09:32 INFO    io.fabric8.jenkins.openshiftsync.OpenShiftUtils initializeOpenShiftClient Current OpenShift Client Configuration: io.fabric8.openshift.client.OpenShiftConfig@3ed8a1f[oapiVersion=v1,openShiftUrl=https://kubernetes.default:443/oapi/v1/,buildTimeout=300000,openshiftApiGroupsEnabled=false,disableApiGroupCheck=false,trustCerts=true,disableHostnameVerification=false,masterUrl=https://kubernetes.default:443/,apiVersion=v1,namespace=jenkins-login,caCertFile=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt,caCertData=<null>,clientCertFile=<null>,clientCertData=<null>,clientKeyFile=<null>,clientKeyData=<null>,clientKeyAlgo=<null>,clientKeyPassphrase=changeit,trustStoreFile=<null>,trustStorePassphrase=<null>,keyStoreFile=<null>,keyStorePassphrase=<null>,authProvider=<null>,requestConfig=io.fabric8.kubernetes.client.RequestConfig@4a09edc1,contexts=[],currentContext=<null>,username=<null>,password=<null>,oauthToken=<null>,watchReconnectInterval=1000,watchReconnectLimit=-1,connectionTimeout=10000,uploadConnectionTimeout=10000,uploadRequestTimeout=120000,requestRetryBackoffLimit=0,requestRetryBackoffInterval=0,requestTimeout=10000,rollingTimeout=900000,scaleTimeout=600000,loggingInterval=20000,websocketTimeout=5000,websocketPingInterval=30000,maxConcurrentRequests=64,maxConcurrentRequestsPerHost=5,impersonateUsername=<null>,oauthTokenProvider=<null>,impersonateGroup=<null>,impersonateGroups=<null>,impersonateExtras=<null>,http2Disable=false,httpProxy=<null>,httpsProxy=<null>,proxyUsername=<null>,proxyPassword=<null>,noProxy={},userAgent=<null>,tlsVersions={TLS_1_2},errorMessages={401=Unauthorized! Configured service account doesn't have access. Service account may have been revoked., 403=Forbidden!Configured service account doesn't have access. Service account may have been revoked.},customHeaders=<null>,autoConfigure=false,file=<null>]
2022-01-26 15:09:32 INFO    io.fabric8.jenkins.openshiftsync.OpenShiftUtils initializeOpenShiftClient New OpenShift client initialized: io.fabric8.openshift.client.DefaultOpenShiftClient@383876d9
```

2022-01-26 15:19 UTC, gabemontero commented
> Testing this manually with cluster-bot, my local build of the plugin seems to work (I'm able to log back into the Jenkins console as kubeadmin).

good to know jenkins console login still worked for you

in case it was not clear, the scenario here is accessing console items, like say a run log, from the command line via curl, supplying kubeadmin's token.

```
# curl -X GET -H "Authorization: Bearer <valid token string>" http://<jenkins svc ip address>/job/<Job name you just executed>/<actual job execution number>/consoleText
if [ $# -eq 4 ]
then
    curl -X GET -H "Authorization: Bearer $1" http://$2/job/$3/$4/consoleText
else
    echo "need 4 params: 1 - token, 2 - svc ip:port, 3 - job name, 4 - job number"
fi

```

2022-01-26 16:49 UTC, gabemontero commented
/lgtm

2022-01-26 18:12 UTC, merged